#!/bin/sh
#
# Time-stamp: <File bu saved at 20:15:48 CET on Sunday 2019-12-08, by janjoris on suus.>
#

bibtex luister
bibtex boeken
pdflatex luister
pdflatex luister
pdflatex boeken
pdflatex boeken
chmod -R u=rwX,g=rwX,o= .
zip boeken *.tex *.bib *.bst *.ent *.pdf bi bu a c d deploy g p pl upl
unzip -v boeken.zip
