#!/bin/sh
#
# Time-stamp: <File bu saved at 11:20:51 CEST on Tuesday 2018-07-31, by janjoris on sinclair.>
#

bibtex luister
bibtex boeken
pdflatex luister
pdflatex luister
pdflatex boeken
pdflatex boeken
chmod -R u=rwX,g=rwX,o= .
zip boeken *.tex *.bib *.bst *.ent *.pdf bi bu c d deploy g p pl upl
unzip -v boeken.zip
