#!/bin/sh
#
# Time-stamp: <File bu saved at 18:11:41 CEST on Wednesday 2018-07-18, by janjoris on hilbert.lan.>
#

bibtex luister
bibtex boeken
pdflatex luister
pdflatex luister
pdflatex boeken
pdflatex boeken
chmod 644 *.pdf
zip boeken *.tex *.bib *.bst *.ent *.pdf bi bu p c d g x kin pl upl
unzip -v boeken.zip
